# Generated by Django 4.0.5 on 2022-06-07 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_seq', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('publisher', models.CharField(default='미정', max_length=100)),
                ('price', models.CharField(default='없음', max_length=100)),
                ('img_url', models.CharField(default='https://via.placeholder.com/150', max_length=100)),
                ('description', models.CharField(default='없음', max_length=100)),
                ('pub_date_2', models.DateField(blank=True, default='', null=True)),
            ],
            options={
                'db_table': 'book_data',
            },
        ),
    ]
